server:
  listen: 8080

  workers: 4

  upstream:
    - id: todos
      url: jsonplaceholder.typicode.com

    - id: posts
      url: jsonplaceholder.typicode.com

    - id: comments
      url: jsonplaceholder.typicode.com

  headers: 
    - key: x-forward-for
      value: '$ip'

    - key: Authorisation
      value: 'Bearer xyz'

  rules:
    - path: /
      upstreams:
        - todos
    
    - path: /posts
      upstreams: 
        - posts

    - path: /todos
      upstreams:
        - todos

    - path: /comments
      upstreams:
        - comments
    